export const START_FETCHING_PARTICIPANTS = 'redux/participants/ START_FETCHING_PARTICIPANTS'
export const SUCCESS_FETCHING_PARTICIPANTS = 'reduc/participants/SUCCESS_FETCHING_PARTICIPANTS'
export const ERROR_FETCHING_PARTICIPANTS = 'reduc/participants/ERROR_FETCHING_PARTICIPANTS'
