export const START_FETCHING_ORGANIZER = 'redux/organizers/START_FETCHING_ORGANIZER'
export const SUCCESS_FETCHING_ORGANIZERS = 'redux/organizers/SUCCESS_FETCHING_ORGANIZERS'
export const ERROR_FETCHING_ORGANIZERS = 'redux/organizers/ERROR_FETCHING_ORGANIZERS'