export const START_FETCHING_LISTS_CATEGORIES = 'redux/lists/START_FETCHING_LISTS_CATEGORIES'
export const SUCCESS_FETCHING_LISTS_CATEGORIES = 'redux/list/SUCCESS_FETCHING_LISTS_CATEGORIES'
export const ERROR_FETCHING_LISTS_CATEGORIES = 'redux/list/ERROR_FETCHING_LISTS_CATEGORIES'

export const START_FETCHING_LISTS_TALENTS = 'redux/lists/START_FETCHING_LISTS_TALENTS'
export const SUCCESS_FETCHING_LISTS_TALENTS = 'redux/list/SUCCESS_FETCHING_LISTS_TALENTS'
export const ERROR_FETCHING_LISTS_TALENTS = 'redux/list/ERROR_FETCHING_LISTS_TALENTS'

export const START_FETCHING_LISTS_EVENTS = 'redux/lists/START_FETCHING_LISTS_EVENTS'
export const SUCCESS_FETCHING_LISTS_EVENTS = 'redux/list/SUCCESS_FETCHING_LISTS_EVENTS'
export const ERROR_FETCHING_LISTS_EVENTS = 'redux/list/ERROR_FETCHING_LISTS_EVENTS'