import {
    START_FETCHING_LISTS_CATEGORIES,
    SUCCESS_FETCHING_LISTS_CATEGORIES,
    ERROR_FETCHING_LISTS_CATEGORIES,
    START_FETCHING_LISTS_TALENTS,
    SUCCESS_FETCHING_LISTS_TALENTS,
    ERROR_FETCHING_LISTS_TALENTS,
    START_FETCHING_LISTS_EVENTS,
    SUCCESS_FETCHING_LISTS_EVENTS,
    ERROR_FETCHING_LISTS_EVENTS
} from './constans'